### PR TITLE
Bench

### PR DESCRIPTION
**Pull request by kornelski**
Separate PR from bigger changes in #54

### CODE REVIEW

**Comment by kaj** [comment]
Hi @kornelski !  Thanks for your continued contributions!  I'm currently on vacation, so there will be a longer delay before I take a good look at your PR:s.

I'm looking forward to trying your patches out when I get home.

**Comment by kaj** [comment]
This seems fine except that rustfmt dislikes an extra space before a comment.

**Comment by kaj** [comment]
Merged, sorry for the long delay.

**Comment by kornelski** [comment]
No problem

**Pull request merged**
